// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRYDP0GsjRL8RzVBS0uVaShJ2_zCsh4o',
    appId: '1:713375412446:web:df9c262eea2168c7b9924f',
    messagingSenderId: '713375412446',
    projectId: 'iffenquiz',
    authDomain: 'iffenquiz.firebaseapp.com',
    storageBucket: 'iffenquiz.appspot.com',
    measurementId: 'G-9C7TJZFRN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAukAnBp8T5qZl7eAS767y0bcQwptSKEW8',
    appId: '1:713375412446:android:b914e50bb3538d44b9924f',
    messagingSenderId: '713375412446',
    projectId: 'iffenquiz',
    storageBucket: 'iffenquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7R0QWL13vbPtZ60Q4LHaHX7Q0dVKLTG0',
    appId: '1:713375412446:ios:b9aa3d13318a68e1b9924f',
    messagingSenderId: '713375412446',
    projectId: 'iffenquiz',
    storageBucket: 'iffenquiz.appspot.com',
    iosBundleId: 'com.example.iffenQuizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7R0QWL13vbPtZ60Q4LHaHX7Q0dVKLTG0',
    appId: '1:713375412446:ios:dc24034a4e55c782b9924f',
    messagingSenderId: '713375412446',
    projectId: 'iffenquiz',
    storageBucket: 'iffenquiz.appspot.com',
    iosBundleId: 'com.example.iffenQuizz.RunnerTests',
  );
}
